import type {
  JobApplication,
  JobDescriptionAnalysis,
  PdiPlan,
  ReconciliationReport,
  ResumeAnalysis,
  ResumeMatchReport,
  ResumeTailoringSuggestions,
} from '../types'

export const resumeAnalysisFixture: ResumeAnalysis = {
  detected_name: 'Pessoa Teste',
  professional_summary: 'Perfil em dados com evidencias de Python e SQL.',
  probable_areas: ['Ciencia de Dados'],
  estimated_level: 'Junior',
  technical_skills: ['Python', 'SQL', 'Power BI'],
  soft_skills: ['comunicacao'],
  experience_summary: 'Projetos de dashboards e indicadores.',
  education_summary: 'Curso de dados.',
  suggested_target_roles: ['Analista de Dados Junior'],
  strengths: ['Python', 'SQL'],
  improvement_points: ['Detalhar resultados'],
  fields_to_confirm: ['Localizacao'],
}

export const jobAnalysisFixture: JobDescriptionAnalysis = {
  title: 'Analista de Dados Junior',
  company: 'Acme',
  seniority: 'Junior',
  modality: 'Remoto',
  location: 'Brasil',
  keywords: ['Python', 'SQL'],
  hard_skills: ['Python', 'SQL'],
  soft_skills: ['comunicacao'],
  tools: ['Power BI'],
  responsibilities: ['Construir dashboards'],
  required_requirements: ['Python'],
  nice_to_have: ['Excel'],
  alerts: [],
  next_steps: ['Comparar com o curriculo'],
}

export const matchReportFixture: ResumeMatchReport = {
  overall_score: 72,
  readiness_level: 'Boa aderencia',
  job_title: 'Analista de Dados Junior',
  resume_summary: 'Curriculo com base em dados.',
  score_breakdown: {
    hard_skills: 30,
    tools: 12,
    soft_skills: 10,
    keywords: 8,
    seniority_area: 8,
  },
  strong_evidence: ['Python', 'SQL'],
  partial_evidence: ['Power BI'],
  missing_requirements: ['Excel'],
  hard_skills_found: ['Python', 'SQL'],
  hard_skills_missing: ['Excel'],
  soft_skills_found: ['comunicacao'],
  soft_skills_missing: [],
  tools_found: ['Power BI'],
  tools_missing: ['Excel'],
  matched_keywords: ['dados'],
  missing_keywords: ['KPIs'],
  strengths: ['Boa base tecnica'],
  critical_gaps: ['Excel'],
  safe_resume_suggestions: ['Evidenciar projetos em Python'],
  do_not_claim: ['Excel avancado'],
  next_steps: ['Gerar sugestoes seguras'],
}

export const reconciliationFixture: ReconciliationReport = {
  focus: 'vaga',
  consistency_score: 82,
  consistency_level: 'coerente',
  profile_resume_conflicts: [],
  profile_job_conflicts: [],
  resume_job_summary: 'Aderência currículo×vaga: 72/100 (Boa aderencia).',
  match_score: 72,
  aligned_fields: ['Nível alinhado', 'Habilidades técnicas com interseção em Python'],
  focus_recommendations: ['Alinhe perfil e currículo ao que a vaga pede.'],
  next_steps: ['Gerar sugestões seguras'],
}

export const tailoringFixture: ResumeTailoringSuggestions = {
  job_title: 'Analista de Dados Junior',
  match_score: 72,
  readiness_level: 'Boa aderencia',
  summary_suggestions: ['Destacar projetos de dados reais'],
  skills_suggestions: ['Priorizar Python e SQL'],
  project_suggestions: ['Publicar dashboard simples'],
  experience_suggestions: ['Separar contexto, acao e resultado'],
  keywords_to_include: ['Python', 'SQL'],
  keywords_to_avoid_claiming: ['Excel avancado'],
  can_highlight_better: ['Python'],
  can_reposition: ['Power BI'],
  needs_evidence: ['Excel'],
  do_not_claim: ['Excel avancado'],
  safety_alerts: ['Nao inventar experiencia'],
  next_steps: ['Gerar PDI'],
}

export const pdiFixture: PdiPlan = {
  target_role: 'Analista de Dados Junior',
  overall_score: 72,
  readiness_level: 'Boa aderencia',
  main_goal: 'Fortalecer Excel e indicadores sem inflar experiencia.',
  priority_gaps: ['Excel'],
  quick_wins: ['Documentar Python'],
  seven_day_plan: ['Revisar requisitos da vaga'],
  thirty_day_plan: ['Criar dashboard'],
  sixty_day_plan: ['Evoluir portfolio'],
  portfolio_projects: ['Dashboard de KPIs'],
  resume_evidence_to_create: ['Projeto verificavel em Excel'],
  study_resources: ['Microsoft Learn Excel'],
  interview_preparation: ['Explicar lacunas com transparencia'],
  next_steps: ['Treinar entrevista'],
}

export const applicationFixture: JobApplication = {
  id: 'app-1',
  titulo: 'Analista de Dados Junior',
  empresa: 'Acme',
  localizacao: 'Remoto',
  link: 'https://example.com/vaga',
  habilidades_correspondentes: 'Python, SQL',
  habilidades_faltantes: 'Excel',
  contagem_correspondencia: '2 de 3',
  status: 'salva',
  data_salva: '2026-06-16T12:00:00Z',
  notas: '',
}
